# Generated by Django 2.1.4 on 2018-12-27 10:30

import ams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_location', models.CharField(max_length=200)),
                ('asset_supplied_by', models.CharField(max_length=200)),
                ('asset_installation_date', models.DateField(max_length=200)),
                ('asset_commissioning_date', models.DateField(max_length=200)),
                ('asset_manufactured_by', models.CharField(max_length=200)),
                ('asset_warranty_expiration_date', models.DateField(max_length=200)),
                ('asset_overhauling_date', models.DateField(max_length=200)),
                ('asset_codallife_date', models.DateField(max_length=200)),
                ('asset_maintainance_procedure', models.FileField(blank=True, upload_to=ams.models.get_resume_folder)),
                ('asset_mainatainance_history', models.CharField(max_length=500)),
                ('asset_test_procedure', models.FileField(blank=True, upload_to=ams.models.get_resume_folder)),
            ],
        ),
    ]
